services:
  - type: web
    name: wedding-chatbot
    env: node
    plan: free
    region: singapore
    buildCommand: |
      cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: |
      cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: OPENROUTER_API_KEY
        sync: false
    rootDir: .
