services:
  - type: web
    name: wedding-chatbot
    env: node
    plan: free
    region: singapore
    buildCommand: |
      npm install
      cd client && npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: OPENROUTER_API_KEY
        sync: false
