services:
  - type: web
    name: wedding-chatbot
    env: node
    plan: free
    region: singapore
    buildCommand: |
      cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: |
      cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: OPENROUTER_API_KEY
        value: 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 # Thay bằng API key thật của bạn
    rootDir: .
